const express = require('express')
const router = express.Router()
const Model = require('../../model')
const products = require('./products')
const users = require('./users')
const passport = require('passport')
router.get('/products', products.getProducts)
router.get('/product/:pid', products.getProduct)
router.get('/users/:uid/cart', users.getUserShoppingCart)
router.get('/users/:uid/cart/items', users.getUserShoppingCartItems)
router.post('/users/:uid/cart/items/:pid', users.addProductToShoppingCart)
router.delete('/users/:uid/cart/items/:pid', users.deleteProductToShoppingCart)
router.delete('/users/:uid/cart/items/:pid/decrease', users.decreaseQtyProductToShoppingCart)
router.post('/users/signin', passport.authenticate('local', {session: false}), users.signInUser)
router.post('/users/signup', users.signUpUser)
router.get('/users/:uid/', users.getUserProfile)
router.get('/users/:uid/orders', users.getUserOrders)
router.post('/users/:uid/orders', users.newOrder)
router.get('/users/:uid/orders/:number', users.getUserOrder)
router.get('/users/:uid/orders/:number/items', users.getUserOrderItems)
module.exports = router;