const express = require('express')
const router = express.Router()
const Model = require('../../model')
const products = require('./products')
const users = require('./users')
const passport = require('passport')
router.get('/products', products.getProducts)
router.get('/product/:pid', products.getProduct)
router.get('/users/:uid/cart', passport.authenticate('jwt', {session: false}), users.getUserShoppingCart)
router.get('/users/:uid/cart/items', passport.authenticate('jwt', {session: false}), users.getUserShoppingCartItems)
router.post('/users/:uid/cart/items/:pid', passport.authenticate('jwt', {session: false}), users.addProductToShoppingCart)
router.delete('/users/:uid/cart/items/:pid', passport.authenticate('jwt', {session: false}), users.deleteProductToShoppingCart)
router.delete('/users/:uid/cart/items/:pid/decrease', passport.authenticate('jwt', {session: false}), users.decreaseQtyProductToShoppingCart)
router.post('/users/signin', passport.authenticate('local', {session: false}), users.signInUser)
router.post('/users/signup', users.signUpUser)
router.get('/users/:uid/', passport.authenticate('jwt', {session: false}), users.getUserProfile)
router.get('/users/:uid/orders', passport.authenticate('jwt', {session: false}), users.getUserOrders)
router.post('/users/:uid/orders', passport.authenticate('jwt', {session: false}), users.newOrder)
router.get('/users/:uid/orders/:number', passport.authenticate('jwt', {session: false}), users.getUserOrder)
router.get('/users/:uid/orders/:number/items', passport.authenticate('jwt', {session: false}), users.getUserOrderItems)
module.exports = router;